"use client";

import React from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";

interface RightPanelProps {
  selectedOpportunityId: string;
}

const RightPanel: React.FC<RightPanelProps> = ({ selectedOpportunityId }) => {
  return (
    <div className="h-full flex flex-col p-4">
      <Card className="flex-grow">
        <CardHeader>
          <CardTitle>Related Information</CardTitle>
        </CardHeader>
        <CardContent className="h-[calc(100%-80px)]"> {/* Adjust height to account for header */}
          <ScrollArea className="h-full w-full pr-4">
            <p className="text-sm text-muted-foreground">
              Details for selected opportunity: <span className="font-semibold text-foreground">{selectedOpportunityId}</span>
            </p>
            <div className="mt-4 space-y-2">
              {/* Placeholder for more detailed content */}
              <p>This panel will show more information about the selected opportunity.</p>
              <p>You can add widgets, related documents, or other relevant data here.</p>
              <p>For example, a small image gallery, activity feed, or contact details.</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</p>
              <p>More content will go here...</
            </p>
            </div>
          </ScrollArea>
        </CardContent>
        {/* You can add a footer here if needed */}
        {/* <CardFooter className="flex justify-end">
          <Button size="sm" className="mr-2">
            Save
          </Button>
          <Button variant="outline" size="sm">
            Cancel
          </Button>
        </CardFooter> */}
      </Card>
    </div>
  );
};

export default RightPanel;